### PR TITLE
RxSwift 5 compatible.

### PR DESCRIPTION
**Pull request by lm2343635**
I have updated the RxSwift version to 5.0
But there is a build error with Carthage, can you solve this issue?

### CODE REVIEW

**Comment by kazuhiro4949** [comment]
@lm2343635 Which version of xcode did you use? You can show it with the following command.

```
xcode-select -p
```

If you use Xcode 10.1, you need to switch the version:

```
sudo xcode-select -s path/to/xcode10.2
```

**Review by kazuhiro4949 — APPROVED** [review]

**Comment by lm2343635** [comment]
Xcode 10.2

**Comment by lm2343635** [comment]
image

**Comment by lm2343635** [comment]
I've fixed the crash by adding RxRelay to the embedded binaries.
Can you merge this PR and update the podspec version?
Thanks! @kazuhiro4949

**Comment by lm2343635** [comment]
By the way, I think it is better to merge this repo into the repo of PagingKit, and use RxPagingKit as a sub module of PagingKit like this

```Ruby
pod 'PagingKit/Rx'
```

**Comment by lm2343635** [comment]
Can you review this if possible. @kazuhiro4949

**Comment by kazuhiro4949** [comment]
@lm2343635 I'm sorry for forgetting this pull request. 
Could you make an issue about sub-module in PagingKit repository?

**Pull request merged**
